### ISSUE TITLE
labels should be exposed

### ISSUE THREAD

**Issue by bharathkkb** [GoogleCloudPlatform/terraform-example-deploy-java-multizone#19]
Labels should be exposed as inputs and plumbed to all resources

**Comment by donmccasland** [comment]
Like this:
# main.tf
resource "google_compute_instance" "default" {
  name         = "test"
  machine_type = "e2-medium"
  zone         = "us-central1-a"
  labels      = var.labels
…
}

resource "google_cloudfunctions_function" "main" {
 name         = "test"
 labels      = var.labels
…
}
